drop table IF EXISTS  yarn.jmxinfototalresource;
CREATE  TABLE if NOT  EXISTS yarn.jmxinfototalresource (
  name                                           VARCHAR(500),
  modelerType                                    VARCHAR(100),
  Queue                                          VARCHAR(100),
  Context                                        VARCHAR(20),
  Hostname                                       VARCHAR(100),
  running_0                                      VARCHAR(20),
  running_60                                     VARCHAR(20),
  running_300                                    VARCHAR(20),
  running_1440                                   VARCHAR(20),

  FairShareMB                                    VARCHAR(20),
  FairShareVCores                                VARCHAR(20),
  SteadyFairShareMB                              VARCHAR(20),
  SteadyFairShareVCores                          VARCHAR(20),
  MinShareMB                                     VARCHAR(20),
  MinShareVCores                                 VARCHAR(20),
  MaxShareMB                                     VARCHAR(20),
  MaxShareVCores                                 VARCHAR(20),

  AppsSubmitted                                  VARCHAR(20),
  AppsRunning                                    VARCHAR(20),
  AppsPending                                    VARCHAR(20),
  AppsCompleted                                  VARCHAR(20),
  AppsKilled                                     VARCHAR(20),
  AppsFailed                                     VARCHAR(20),
  AllocatedMB                                    VARCHAR(20),
  AllocatedVCores                                VARCHAR(20),
  AllocatedContainers                            VARCHAR(20),
  AggregateContainersAllocated                   VARCHAR(20),
  AggregateContainersReleased                    VARCHAR(20),
  AvailableMB                                    VARCHAR(20),
  AvailableVCores                                VARCHAR(20),
  PendingMB                                      VARCHAR(20),
  PendingVCores                                  VARCHAR(20),
  PendingContainers                              VARCHAR(20),
  ReservedMB                                     VARCHAR(20),
  ReservedVCores                                 VARCHAR(20),
  ReservedContainers                             VARCHAR(20),
  ActiveUsers                                    VARCHAR(20),
  ActiveApplications                             VARCHAR(20),
  AppAttemptFirstContainerAllocationDelayNumOps  VARCHAR(20),
  AppAttemptFirstContainerAllocationDelayAvgTime VARCHAR(20),
  viewtime                                       VARCHAR(20),
  viewdate                                       VARCHAR(20)
)
